//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laan.ObjectSync.Client.MessageServer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeDefinition", Namespace="http://schemas.datacontract.org/2004/07/Laan.ObjectSync")]
    [System.SerializableAttribute()]
    public partial class TypeDefinition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MessageServer.IMessageServer")]
    public interface IMessageServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageServer/RegisterClient", ReplyAction="http://tempuri.org/IMessageServer/RegisterClientResponse")]
        Laan.ObjectSync.Client.MessageServer.TypeDefinition[] RegisterClient(System.Guid clientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageServer/GetMessages", ReplyAction="http://tempuri.org/IMessageServer/GetMessagesResponse")]
        byte[][] GetMessages(System.Guid clientID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IMessageServerChannel : Laan.ObjectSync.Client.MessageServer.IMessageServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class MessageServerClient : System.ServiceModel.ClientBase<Laan.ObjectSync.Client.MessageServer.IMessageServer>, Laan.ObjectSync.Client.MessageServer.IMessageServer {
        
        public MessageServerClient() {
        }
        
        public MessageServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Laan.ObjectSync.Client.MessageServer.TypeDefinition[] RegisterClient(System.Guid clientID) {
            return base.Channel.RegisterClient(clientID);
        }
        
        public byte[][] GetMessages(System.Guid clientID) {
            return base.Channel.GetMessages(clientID);
        }
    }
}
